// Mocks generated by Mockito 5.4.6 from annotations
// in architecture_study/test/data/repositories/auth/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:architecture_study/data/services/local/secure_storage/auth/auth_secure_storage_service.dart'
    as _i10;
import 'package:architecture_study/data/services/local/secure_storage/auth/auth_secure_storage_service_impl.dart'
    as _i11;
import 'package:architecture_study/data/services/local/secure_storage/secure_storage_service.dart'
    as _i3;
import 'package:architecture_study/data/services/remote/api/api_client.dart'
    as _i2;
import 'package:architecture_study/data/services/remote/api/auth/auth_api_service.dart'
    as _i4;
import 'package:architecture_study/data/services/remote/api/auth/auth_api_service_impl.dart'
    as _i9;
import 'package:architecture_study/data/services/remote/dto/login/login_dto.dart'
    as _i7;
import 'package:architecture_study/utils/result.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageService_1 extends _i1.SmartFake
    implements _i3.SecureStorageService {
  _FakeSecureStorageService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i4.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<_i7.LoginDto>> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i5.Future<_i6.Result<_i7.LoginDto>>.value(
              _i8.dummyValue<_i6.Result<_i7.LoginDto>>(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.LoginDto>>);
}

/// A class which mocks [AuthApiServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiServiceImpl extends _i1.Mock
    implements _i9.AuthApiServiceImpl {
  MockAuthApiServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i5.Future<_i6.Result<_i7.LoginDto>> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i5.Future<_i6.Result<_i7.LoginDto>>.value(
              _i8.dummyValue<_i6.Result<_i7.LoginDto>>(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.LoginDto>>);
}

/// A class which mocks [AuthSecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSecureStorageService extends _i1.Mock
    implements _i10.AuthSecureStorageService {
  MockAuthSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAccessToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAccessToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getRefreshToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [AuthSecureStorageServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSecureStorageServiceImpl extends _i1.Mock
    implements _i11.AuthSecureStorageServiceImpl {
  MockAuthSecureStorageServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SecureStorageService get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeSecureStorageService_1(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i3.SecureStorageService);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAccessToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAccessToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getRefreshToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
