// Mocks generated by Mockito 5.4.6 from annotations
// in architecture_study/test/data/repositories/auth/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:architecture_study/data/services/local/preferences/auth/auth_preferences_service.dart'
    as _i10;
import 'package:architecture_study/data/services/local/preferences/auth/auth_preferences_service_impl.dart'
    as _i11;
import 'package:architecture_study/data/services/local/preferences/shared_preferences_service.dart'
    as _i3;
import 'package:architecture_study/data/services/remote/api/api_client.dart'
    as _i2;
import 'package:architecture_study/data/services/remote/api/auth/auth_api_service.dart'
    as _i4;
import 'package:architecture_study/data/services/remote/api/auth/auth_api_service_impl.dart'
    as _i9;
import 'package:architecture_study/data/services/remote/dto/login/login_dto.dart'
    as _i7;
import 'package:architecture_study/utils/result.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferencesService_1 extends _i1.SmartFake
    implements _i3.SharedPreferencesService {
  _FakeSharedPreferencesService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i4.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<_i7.LoginDto>> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<_i6.Result<_i7.LoginDto>>.value(
              _i8.dummyValue<_i6.Result<_i7.LoginDto>>(
                this,
                Invocation.method(#login, []),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.LoginDto>>);
}

/// A class which mocks [AuthApiServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiServiceImpl extends _i1.Mock
    implements _i9.AuthApiServiceImpl {
  MockAuthApiServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i5.Future<_i6.Result<_i7.LoginDto>> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<_i6.Result<_i7.LoginDto>>.value(
              _i8.dummyValue<_i6.Result<_i7.LoginDto>>(
                this,
                Invocation.method(#login, []),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.LoginDto>>);
}

/// A class which mocks [AuthPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthPreferencesService extends _i1.Mock
    implements _i10.AuthPreferencesService {
  MockAuthPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAccessToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAccessToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getRefreshToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [AuthPreferencesServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthPreferencesServiceImpl extends _i1.Mock
    implements _i11.AuthPreferencesServiceImpl {
  MockAuthPreferencesServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SharedPreferencesService get generalPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#generalPreferences),
            returnValue: _FakeSharedPreferencesService_1(
              this,
              Invocation.getter(#generalPreferences),
            ),
          )
          as _i3.SharedPreferencesService);

  @override
  String getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAccessToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAccessToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getRefreshToken, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
