// Mocks generated by Mockito 5.4.6 from annotations
// in architecture_study/test/data/repositories/todos/todo_repository_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:architecture_study/data/services/api_client.dart' as _i2;
import 'package:architecture_study/data/services/models/todos/todos_model.dart'
    as _i6;
import 'package:architecture_study/data/services/result.dart' as _i5;
import 'package:architecture_study/data/services/todos/todos_service.dart'
    as _i3;
import 'package:architecture_study/data/services/todos/todos_service_api.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodosService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodosService extends _i1.Mock implements _i3.TodosService {
  MockTodosService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<_i6.TodosModel>> fetch() =>
      (super.noSuchMethod(
            Invocation.method(#fetch, []),
            returnValue: _i4.Future<_i5.Result<_i6.TodosModel>>.value(
              _i7.dummyValue<_i5.Result<_i6.TodosModel>>(
                this,
                Invocation.method(#fetch, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.TodosModel>>);

  @override
  _i4.Future<_i5.Result<_i6.TodoModel>> fetchById({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchById, [], {#id: id}),
            returnValue: _i4.Future<_i5.Result<_i6.TodoModel>>.value(
              _i7.dummyValue<_i5.Result<_i6.TodoModel>>(
                this,
                Invocation.method(#fetchById, [], {#id: id}),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.TodoModel>>);
}

/// A class which mocks [TodoServiceAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoServiceAPI extends _i1.Mock implements _i8.TodoServiceAPI {
  MockTodoServiceAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i4.Future<_i5.Result<_i6.TodosModel>> fetch() =>
      (super.noSuchMethod(
            Invocation.method(#fetch, []),
            returnValue: _i4.Future<_i5.Result<_i6.TodosModel>>.value(
              _i7.dummyValue<_i5.Result<_i6.TodosModel>>(
                this,
                Invocation.method(#fetch, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.TodosModel>>);

  @override
  _i4.Future<_i5.Result<_i6.TodoModel>> fetchById({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchById, [], {#id: id}),
            returnValue: _i4.Future<_i5.Result<_i6.TodoModel>>.value(
              _i7.dummyValue<_i5.Result<_i6.TodoModel>>(
                this,
                Invocation.method(#fetchById, [], {#id: id}),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.TodoModel>>);
}
