name: Auto approve and merge

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v5

      - name: Approve and enable auto-merge
        run: |
          # 承認レビューを付与
          gh pr review "${{ github.event.number }}" --approve
          # auto-merge を有効化（Squash マージ）
          gh pr merge "${{ github.event.number }}" --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}