name: Flutter CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Flutterのセットアップ
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Flutterバージョン確認
        run: flutter --version

      - name: Flutter SDKのパスを環境変数に追加
        run: echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Pubキャッシュの復元
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Flutterクリーン
        run: flutter clean

      - name: Dart/Flutterの依存関係を取得
        run: flutter pub get

      - name: Dartコードの修正
        run: dart fix --apply .

      - name: Dartコードのフォーマット
        run: dart format .

      - name: Dartコードの解析
        run: dart analyze

      - name: Flutterコードの解析
        run: flutter analyze

      - name: テストの実行とカバレッジレポートの生成
        run: flutter test --coverage

      #      - name: Slack通知
      #        if: ${{ always() }}
      #        uses: slackapi/slack-github-action@v2.1.1
      #        with:
      #          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      #          webhook-type: incoming-webhook
      #          payload: |
      #            {
      #              "text": "GitHub Actionsの結果: ${{ job.status }}\nリポジトリ: ${{ github.repository }}\nPull Request: ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})\nURL: ${{ github.event.pull_request.html_url }}\nブランチ: ${{ github.head_ref }}\nコミット: ${{ github.event.pull_request.head.sha }}\nコミットメッセージ: ${{ github.event.pull_request.head.message }}"
      #            }

      - name: Slack通知
        if: ${{ always() }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"


#on: [ push ]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo 'build'
#
#  test1:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - run: echo 'test1'
#
#  test2:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - run: echo 'test2'
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [ test1, test2 ]
#    steps:
#      - run: echo 'deploy'

#
#
#
#
#name: Slack Notification
#
#on: [ push ]
#
#env:
#  SLACK_USERNAME: DeployBot
#  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
#  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
#
#jobs:
#  slackNotification:
#    name: Slack-Notification
#    runs-on: ubuntu-latest
#
#    steps:
#      #-- Gitリポジトリの内容を取得 --#
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      #-- Slack通知 --#
#      # 成功
#      - name: Slack Notification on Success
#        uses: rtCamp/action-slack-notify@v2
#        if: ${{ success() }}
#        env:
#          SLACK_TITLE: Deploy / Success
#          SLACK_COLOR: good
#          SLACK_MESSAGE: 完了しました 🚀
#
#      # 失敗
#      - name: Slack Notification on Failure
#        uses: rtCamp/action-slack-notify@v2
#        if: ${{ failure() }}
#        env:
#          SLACK_TITLE: Deploy / Failure
#          SLACK_COLOR: danger
#          SLACK_MESSAGE: 失敗しました 😢